### ISSUE TITLE
v1.1.0 missing build directory

### ISSUE THREAD

**Issue by dotNetDR** [stackpath/node-grpc-error-details#19]
v1.0.0 is ok, build dir found.
![image](https://user-images.githubusercontent.com/926166/123060859-b03fd900-d43d-11eb-83e7-e25ff3b481a5.png)  

v1.1.0 missing build directory, must `npm run build` when `npm i`
![image](https://user-images.githubusercontent.com/926166/123061016-d06f9800-d43d-11eb-86c1-1033733cb886.png)

sorry my bad english.

**Comment by klaude** [comment]
Thanks for pointing this out, @dotNetDR. We'll add the missing directory today in version 1.1.1. I'll update this issue when it should be ready to try.

**Comment by klaude** [comment]
Thanks for waiting! I've published v1.1.2 with the missing `build/` directory. Please let us know if this does the trick. Thanks!

**Comment by dotNetDR** [comment]
step 1: install pkg
```
npm i @stackpath/node-grpc-error-details
```

step 2: write sample app to test
```
const tool = require('@stackpath/node-grpc-error-details')
console.log(tool.Code)
```

step 3: run app, throw error.
```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'google-protobuf'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (***/demo/node_modules/@stackpath/node-grpc-error-details/build/generated/status_pb.js:14:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

When i manually install pkg `google-protobuf`, the v1.1.2 is working
```
$ npm i google-protobuf

$ node index.js
stdout --->>
{ OK: 0,
  CANCELLED: 1,
  UNKNOWN: 2,
  INVALID_ARGUMENT: 3,
  DEADLINE_EXCEEDED: 4,
  NOT_FOUND: 5,
  ALREADY_EXISTS: 6,
  PERMISSION_DENIED: 7,
  UNAUTHENTICATED: 16,
  RESOURCE_EXHAUSTED: 8,
  FAILED_PRECONDITION: 9,
  ABORTED: 10,
  OUT_OF_RANGE: 11,
  UNIMPLEMENTED: 12,
  INTERNAL: 13,
  UNAVAILABLE: 14,
  DATA_LOSS: 15 }
```

`google-protobuf` need to move `devDependencies ` to `dependencies ` in `package.json`?
https://github.com/stackpath/node-grpc-error-details/blob/87f5940e515ce7bf07596d92a4624fca54a904e5/package.json#L9-L17

**Comment by dotNetDR** [comment]
the reason: package-lock.json can not find pkg `google-protobuf`, when `npm i @stackpath/node-grpc-error-details`
![image](https://user-images.githubusercontent.com/926166/123361903-68869200-d5a2-11eb-9683-df2b00774fc5.png)

**Comment by klaude** [comment]
That's odd. It installed `google-protobuf` for me in an empty directory:

```bash
$ uname -a
Darwin <snip> 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

$ node --version
v15.12.0

$ npm --version
7.6.3

$ npm i @stackpath/node-grpc-error-details
npm WARN deprecated @types/protobufjs@6.0.0: This is a stub types definition for protobufjs (https://github.com/dcodeIO/ProtoBuf.js). protobufjs provides its own type definitions, so you don't need @types/protobufjs installed!
npm WARN deprecated grpc@1.24.10: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.

added 95 packages, and audited 96 packages in 4m

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ cat >> index.js
const tool = require('@stackpath/node-grpc-error-details')
console.log(tool.Code)

$ node ./index.js
{
  OK: 0,
  CANCELLED: 1,
  UNKNOWN: 2,
  INVALID_ARGUMENT: 3,
  DEADLINE_EXCEEDED: 4,
  NOT_FOUND: 5,
  ALREADY_EXISTS: 6,
  PERMISSION_DENIED: 7,
  UNAUTHENTICATED: 16,
  RESOURCE_EXHAUSTED: 8,
  FAILED_PRECONDITION: 9,
  ABORTED: 10,
  OUT_OF_RANGE: 11,
  UNIMPLEMENTED: 12,
  INTERNAL: 13,
  UNAVAILABLE: 14,
  DATA_LOSS: 15
}

$ jq '.packages."node_modules/google-protobuf"' ./package-lock.json
{
  "version": "3.17.3",
  "resolved": "https://registry.npmjs.org/google-protobuf/-/google-protobuf-3.17.3.tgz",
  "integrity": "sha512-OVPzcSWIAJ+d5yiHyeaLrdufQtrvaBrF4JQg+z8ynTkbO3uFcujqXszTumqg1cGsAsjkWnI+M5B1xZ19yR4Wyg==",
  "peer": true
}
```

Which versions of node and npm are you using? Can you share the output from `npm i @stackpath/node-grpc-error-details`? I'm curious if there any warnings from that command. 

I suspect that npm isn't installing [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/). `google-protobuf` is set as a peer dependency in `package.json`, and you may need to either use a compatible version of yarn or npm or declare `google-protobuf` as a dependency in your app's `package.json` file to bring it in.

**Comment by dotNetDR** [comment]
my nodejs environment 
```
$ node -v
v10.15.3

$ npm -v
6.4.1
```

**Comment by dotNetDR** [comment]
```
$ npm i @stackpath/node-grpc-error-details --verbose
npm info it worked if it ends with ok
npm verb cli [ '***.nvm/versions/node/v10.15.3/bin/node',
npm verb cli   '***.nvm/versions/node/v10.15.3/bin/npm',
npm verb cli   'i',
npm verb cli   '@stackpath/node-grpc-error-details',
npm verb cli   '--verbose' ]
npm info using npm@6.4.1
npm info using node@v10.15.3
npm verb npm-session c7ec4e30f9da0bcf
npm http fetch GET 304 https://registry.npm.taobao.org/@stackpath%2fnode-grpc-error-details 330ms (from cache)
npm timing stage:loadCurrentTree Completed in 477ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
npm http fetch GET 304 https://registry.npm.taobao.org/@types%2fprotobufjs 66ms (from cache)
npm WARN deprecated @types/protobufjs@6.0.0: This is a stub types definition for protobufjs (https://github.com/dcodeIO/ProtoBuf.js). protobufjs provides its own type definitions, so you don't need @types/protobufjs installed!
npm http fetch GET 304 https://registry.npm.taobao.org/@types%2fgoogle-protobuf 212ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@types%2fnode 219ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/protobufjs 123ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2faspromise 154ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2fcodegen 154ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2feventemitter 154ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/long 82ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2futf8 315ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2ffloat 322ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2finquire 319ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2ffetch 324ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2fpath 320ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2fpool 320ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@protobufjs%2fbase64 331ms (from cache)
npm http fetch GET 304 https://registry.npm.taobao.org/@types%2flong 174ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 730ms
npm timing stage:loadIdealTree Completed in 741ms
npm timing stage:generateActionsToTake Completed in 7ms
npm verb correctMkdir ***.npm/_locks correctMkdir not in flight; initializing
npm timing audit compress Completed in 2ms
npm info audit Submitting payload of 891bytes
npm verb lock using ***.npm/_locks/staging-75b24713ee5b7069.lock for ***nodejs/demo/node_modules/.staging
npm http fetch POST 400 http://registry.npm.shimo.run/-/npm/v1/security/audits/quick 201ms
npm http fetch POST 404 https://registry.npm.taobao.org/-/npm/v1/security/audits/quick 293ms
npm timing action:extract Completed in 788ms
npm timing action:finalize Completed in 31ms
npm timing action:refresh-package-json Completed in 97ms
npm info lifecycle @protobufjs/aspromise@1.1.2~preinstall: @protobufjs/aspromise@1.1.2
npm info lifecycle @protobufjs/base64@1.1.2~preinstall: @protobufjs/base64@1.1.2
npm info lifecycle @protobufjs/codegen@2.0.4~preinstall: @protobufjs/codegen@2.0.4
npm info lifecycle @protobufjs/eventemitter@1.1.0~preinstall: @protobufjs/eventemitter@1.1.0
npm info lifecycle @protobufjs/float@1.0.2~preinstall: @protobufjs/float@1.0.2
npm info lifecycle @protobufjs/inquire@1.1.0~preinstall: @protobufjs/inquire@1.1.0
npm info lifecycle @protobufjs/fetch@1.1.0~preinstall: @protobufjs/fetch@1.1.0
npm info lifecycle @protobufjs/path@1.1.2~preinstall: @protobufjs/path@1.1.2
npm info lifecycle @protobufjs/pool@1.1.0~preinstall: @protobufjs/pool@1.1.0
npm info lifecycle @protobufjs/utf8@1.1.0~preinstall: @protobufjs/utf8@1.1.0
npm info lifecycle @types/long@4.0.1~preinstall: @types/long@4.0.1
npm info lifecycle @types/node@15.12.4~preinstall: @types/node@15.12.4
npm info lifecycle long@4.0.0~preinstall: long@4.0.0
npm info lifecycle protobufjs@6.11.2~preinstall: protobufjs@6.11.2
npm info lifecycle @types/google-protobuf@3.15.2~preinstall: @types/google-protobuf@3.15.2
npm info lifecycle @types/protobufjs@6.0.0~preinstall: @types/protobufjs@6.0.0
npm info lifecycle @stackpath/node-grpc-error-details@1.1.2~preinstall: @stackpath/node-grpc-error-details@1.1.2
npm timing action:preinstall Completed in 30ms
npm info linkStuff @protobufjs/aspromise@1.1.2
npm info linkStuff @protobufjs/base64@1.1.2
npm info linkStuff @protobufjs/codegen@2.0.4
npm info linkStuff @protobufjs/eventemitter@1.1.0
npm info linkStuff @protobufjs/float@1.0.2
npm info linkStuff @protobufjs/inquire@1.1.0
npm info linkStuff @protobufjs/fetch@1.1.0
npm info linkStuff @protobufjs/path@1.1.2
npm info linkStuff @protobufjs/pool@1.1.0
npm info linkStuff @protobufjs/utf8@1.1.0
npm info linkStuff @types/long@4.0.1
npm info linkStuff @types/node@15.12.4
npm info linkStuff long@4.0.0
npm info linkStuff protobufjs@6.11.2
npm verb linkBins [ { pbjs: 'bin/pbjs', pbts: 'bin/pbts' },
npm verb linkBins   '***nodejs/demo/node_modules/.bin',
npm verb linkBins   false ]
npm info linkStuff @types/google-protobuf@3.15.2
npm info linkStuff @types/protobufjs@6.0.0
npm info linkStuff @stackpath/node-grpc-error-details@1.1.2
npm timing action:build Completed in 13ms
npm info lifecycle @protobufjs/aspromise@1.1.2~install: @protobufjs/aspromise@1.1.2
npm info lifecycle @protobufjs/base64@1.1.2~install: @protobufjs/base64@1.1.2
npm info lifecycle @protobufjs/codegen@2.0.4~install: @protobufjs/codegen@2.0.4
npm info lifecycle @protobufjs/eventemitter@1.1.0~install: @protobufjs/eventemitter@1.1.0
npm info lifecycle @protobufjs/float@1.0.2~install: @protobufjs/float@1.0.2
npm info lifecycle @protobufjs/inquire@1.1.0~install: @protobufjs/inquire@1.1.0
npm info lifecycle @protobufjs/fetch@1.1.0~install: @protobufjs/fetch@1.1.0
npm info lifecycle @protobufjs/path@1.1.2~install: @protobufjs/path@1.1.2
npm info lifecycle @protobufjs/pool@1.1.0~install: @protobufjs/pool@1.1.0
npm info lifecycle @protobufjs/utf8@1.1.0~install: @protobufjs/utf8@1.1.0
npm info lifecycle @types/long@4.0.1~install: @types/long@4.0.1
npm info lifecycle @types/node@15.12.4~install: @types/node@15.12.4
npm info lifecycle long@4.0.0~install: long@4.0.0
npm info lifecycle protobufjs@6.11.2~install: protobufjs@6.11.2
npm info lifecycle @types/google-protobuf@3.15.2~install: @types/google-protobuf@3.15.2
npm info lifecycle @types/protobufjs@6.0.0~install: @types/protobufjs@6.0.0
npm info lifecycle @stackpath/node-grpc-error-details@1.1.2~install: @stackpath/node-grpc-error-details@1.1.2
npm timing action:install Completed in 5ms
npm info lifecycle @protobufjs/aspromise@1.1.2~postinstall: @protobufjs/aspromise@1.1.2
npm info lifecycle @protobufjs/base64@1.1.2~postinstall: @protobufjs/base64@1.1.2
npm info lifecycle @protobufjs/codegen@2.0.4~postinstall: @protobufjs/codegen@2.0.4
npm info lifecycle @protobufjs/eventemitter@1.1.0~postinstall: @protobufjs/eventemitter@1.1.0
npm info lifecycle @protobufjs/float@1.0.2~postinstall: @protobufjs/float@1.0.2
npm info lifecycle @protobufjs/inquire@1.1.0~postinstall: @protobufjs/inquire@1.1.0
npm info lifecycle @protobufjs/fetch@1.1.0~postinstall: @protobufjs/fetch@1.1.0
npm info lifecycle @protobufjs/path@1.1.2~postinstall: @protobufjs/path@1.1.2
npm info lifecycle @protobufjs/pool@1.1.0~postinstall: @protobufjs/pool@1.1.0
npm info lifecycle @protobufjs/utf8@1.1.0~postinstall: @protobufjs/utf8@1.1.0
npm info lifecycle @types/long@4.0.1~postinstall: @types/long@4.0.1
npm info lifecycle @types/node@15.12.4~postinstall: @types/node@15.12.4
npm info lifecycle long@4.0.0~postinstall: long@4.0.0
npm info lifecycle protobufjs@6.11.2~postinstall: protobufjs@6.11.2

> protobufjs@6.11.2 postinstall ***nodejs/demo/node_modules/protobufjs
> node scripts/postinstall

npm verb lifecycle protobufjs@6.11.2~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle protobufjs@6.11.2~postinstall: PATH: ***.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:***nodejs/demo/node_modules/protobufjs/node_modules/.bin:***nodejs/demo/node_modules/.bin:***.nvm/versions/node/v10.15.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go1.16.2/bin:***go/bin:***flutter/bin:***flutter/.pub-cache/bin:***flutter/bin/cache/dart-sdk/bin:***apache-ant-1.9.14/bin:***gradle-3.3/bin:***apache-maven-3.6.1/bin
npm verb lifecycle protobufjs@6.11.2~postinstall: CWD: ***nodejs/demo/node_modules/protobufjs
npm info lifecycle @types/google-protobuf@3.15.2~postinstall: @types/google-protobuf@3.15.2
npm info lifecycle @types/protobufjs@6.0.0~postinstall: @types/protobufjs@6.0.0
npm info lifecycle @stackpath/node-grpc-error-details@1.1.2~postinstall: @stackpath/node-grpc-error-details@1.1.2
npm timing action:postinstall Completed in 126ms
npm verb unlock done using ***.npm/_locks/staging-75b24713ee5b7069.lock for ***nodejs/demo/node_modules/.staging
npm timing stage:executeActions Completed in 1151ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 2389ms
npm verb saving [ { name: '@stackpath/node-grpc-error-details',
npm verb saving     spec: '^1.1.2',
npm verb saving     save: 'dependencies' } ]
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm notice created a lockfile as package-lock.json. You should commit this file.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN @stackpath/node-grpc-error-details@1.1.2 requires a peer of google-protobuf@>=3 but none is installed. You must install peer dependencies yourself.
npm WARN @stackpath/node-grpc-error-details@1.1.2 requires a peer of grpc@>=1 but none is installed. You must install peer dependencies yourself.
npm WARN demo@1.0.0 No description
npm WARN demo@1.0.0 No repository field.

+ @stackpath/node-grpc-error-details@1.1.2
added 17 packages from 47 contributors in 2.425s
npm verb exit [ 0, true ]
npm timing npm Completed in 2754ms
npm info ok
```

**Comment by klaude** [comment]
Thanks for posting that! I'm not sure why `google-protobuf` are `grpc` are peer dependencies since they're used in `src/generated/`. I'll promote them to regular dependencies and publish a new release. That should clear this up. I'll comment on this issue when that's done.

**Comment by klaude** [comment]
Thanks for your patience. We've published version 1.1.3 with the dependency changes. It should look better for npm 6 users. Please give it a try and let us know what you think!

**Comment by dotNetDR** [comment]
npm 6 working, thanks

**Comment by klaude** [comment]
Excellent! I'm glad it's working now. Thanks for opening the issue, and please let us know if you spot anything else.
